version: "3"

services:
  nodeapp1:
    image: nodeapp
    ports:
      - "2222:9999"
    environment:
      APPID: 2222
    # Add any other configuration options if needed

  nodeapp2:
    image: nodeapp
    ports:
      - "3333:9999"
    environment:
      APPID: 3333
    # Add any other configuration options if needed

  nodeapp3:
    image: nodeapp
    ports:
      - "4444:9999"
    environment:
      APPID: 4444
    # Add any other configuration options if needed

  nodeapp4:
    image: nodeapp
    ports:
      - "5555:9999"
    environment:
      APPID: 5555
    # Add any other configuration options if needed

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_configuration/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3
      - nodeapp4
